apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: prometheus-stack-grafana-service
  namespace: monitoring
spec:
  ports:
  - nodePort: 30006
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: NodePort
